### ISSUE TITLE
Storybook Example: Login Screen

### ISSUE THREAD

**Issue by TheTaz25** [TheTaz25/courner#14]
**What example are you missing?**
I want a Example Login Screen that shows usage of input components with layout components. Example should include inputs for user + password, checkbox for "remember me", link to "forgot password" and button to do the login.

**Design/Style**
- [ ] The input fields should be located centralized.
- [ ] The input fields should be contained on a paper component with elevation.
- [ ] There is a title (h1) that introduces the user with a messages to log in.
- [ ] The title's variant can be changed with controls
- [ ] Input for username with errortext can be changed via controls
- [ ] Input for password with errortext can be changed via controls
- [ ] Checkbox for remember me is included
- [ ] Link for "Forgot Password" is displayed (no linking)
- [ ] Button for "Register" and "Login", Login is primary (no actions)

**Added Value**
First example, usage of different inputs with some data display components together with some layouting

**Missing Components to fulfil**
- [ ] InputWrapper Component (see #5 )
- [ ] Center Component (TBD)
